### ISSUE TITLE
Update ESLint

### ISSUE THREAD

**Issue by svbergerem** [ocke/eslintrb#2]
ESLint v2.4.0 has been released a few days ago while this repo still uses a version somewhere between v2.0.0-beta.1 and v2.0.0-beta.2. It would be great if you could release a new version which updates ESLint to the latest stable version.

**Comment by doits** [comment]
see #3 for a PR with update to 2.7.0

**Comment by ocke** [comment]
Sorry for the late repsonse @svbergerem 

We moved this repo to https://github.com/zendesk/eslintrb/

And we bumped the version! :-)

**Comment by svbergerem** [comment]
@ocke Thank you! :)
